name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-server:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.4.11'
      SERVERPOD_PASSWORD_database: 'X8KnFSqobeStLqJrPB3CuTDCjsyBHryQ'
      SERVERPOD_PASSWORD_redis: '2XT20_AOcrSKMolqKjzIZoyWxFnmWwxY'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.7'

      - name: Start containers
        working-directory: picolemon_server
        run: docker compose up --quiet-pull --build -d

      - name: Install dependencies
        run: flutter pub get

      - name: Install Serverpod CLI
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: picolemon_server
        run: serverpod generate

      - name: Run tests
        working-directory: picolemon_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: picolemon_server
        run: docker compose down -v

  test-games:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.7'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        working-directory: picolemon_games
        run: dart test
